version: "3"
services:
  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"
    command: redis-server --notify-keyspace-events Ex
    volumes:
      - redis_data:/data
    networks:
      - backend_network

  mongodb:
    image: mongo
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: chatdb
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  redis_data: