SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE recruitment_user;
TRUNCATE TABLE voter;
TRUNCATE TABLE user_job_skill;
TRUNCATE TABLE post;
TRUNCATE TABLE job_posting_job_skill;
TRUNCATE TABLE job_posting;
TRUNCATE TABLE job_skill;
TRUNCATE TABLE chat;
TRUNCATE TABLE site_user;
TRUNCATE TABLE category;

SET REFERENTIAL_INTEGRITY TRUE;